repos:
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
        args: [--config=pyproject.toml]
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
      args: [--settings-path=pyproject.toml]
-   repo: https://github.com/csachs/pyproject-flake8/
    rev: v0.0.1a5
    hooks:
    -  id: pyproject-flake8
       name: pyproject-flake8
       args: [--config=pyproject.toml]
